/*
 * PROJECT:     ReactOS VirtIO GPU miniport video driver
 * LICENSE:     GPL-2.0-or-later (https://spdx.org/licenses/GPL-2.0-or-later)
 * PURPOSE:     IOCtl definitions for Virtio Virgl GPU
 * COPYRIGHT:   Copyright 2023 Jesús Sanz del Rey (jesussanz2003@gmail.com)
 */

#pragma once

#ifndef _WDMDDK_
#include <winnt.h>
#endif

enum virtio_gpu_formats {
    VIRTIO_GPU_FORMAT_B8G8R8A8_UNORM  = 1,
    VIRTIO_GPU_FORMAT_B8G8R8X8_UNORM  = 2,
    VIRTIO_GPU_FORMAT_A8R8G8B8_UNORM  = 3,
    VIRTIO_GPU_FORMAT_X8R8G8B8_UNORM  = 4,

    VIRTIO_GPU_FORMAT_R8G8B8A8_UNORM  = 67,
    VIRTIO_GPU_FORMAT_X8B8G8R8_UNORM  = 68,

    VIRTIO_GPU_FORMAT_A8B8G8R8_UNORM  = 121,
    VIRTIO_GPU_FORMAT_R8G8B8X8_UNORM  = 134,
};

typedef struct _VIDEO_CREATE_2D_RESOURCE {
    ULONG Width;
    ULONG Height;
    ULONG Format;
} VIDEO_CREATE_2D_RESOURCE, *PVIDEO_CREATE_2D_RESOURCE;

typedef struct _VIDEO_RESOURCE_ID {
    ULONG ResourceID;
} VIDEO_RESOURCE_ID, *PVIDEO_RESOURCE_ID;

typedef struct _VIDEO_TRANSFER_2D {
    ULONG ResourceID;
    ULONG X;
    ULONG Y;
    ULONG Width;
    ULONG Height;
    ULONG BufferLength;
    UCHAR Buffer[];
} VIDEO_TRANSFER_2D, *PVIDEO_TRANSFER_2D;

typedef struct _VIDEO_CURSOR {
    ULONG ResourceID;
    ULONG X;
    ULONG Y;
    ULONG HotX; //Not used on move
    ULONG HotY; //Not used on move
} VIDEO_CURSOR, *PVIDEO_CURSOR;

typedef struct _VIDEO_CREATE_CONTEXT {
    ULONG NameLength;
    UCHAR Name[64];
} VIDEO_CREATE_CONTEXT, *PVIDEO_CREATE_CONTEXT;

#define IOCTL_VIRTIOGPU_CREATE_2D_RESOURCE \
  CTL_CODE(FILE_DEVICE_VIDEO, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_VIRTIOGPU_RESOURCE_TRANSFER_2D \
  CTL_CODE(FILE_DEVICE_VIDEO, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_VIRTIOGPU_RESOURCE_FLUSH_SCREEN \
  CTL_CODE(FILE_DEVICE_VIDEO, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_VIRTIOGPU_UPDATE_CURSOR \
  CTL_CODE(FILE_DEVICE_VIDEO, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_VIRTIOGPU_MOVE_CURSOR \
  CTL_CODE(FILE_DEVICE_VIDEO, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_VIRTIOGPU_CREATE_CONTEXT \
  CTL_CODE(FILE_DEVICE_VIDEO, 0x820, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_VIRTIOGPU_SET_CONTEXT \
  CTL_CODE(FILE_DEVICE_VIDEO, 0x821, METHOD_BUFFERED, FILE_ANY_ACCESS)
